// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcDDdNXYNd83QFnAWkIm65RRPpLqw6uCg',
    appId: '1:912550072493:web:68fa2dfa5a629ab0b4f624',
    messagingSenderId: '912550072493',
    projectId: 'brain-boost-flashcard',
    authDomain: 'brain-boost-flashcard.firebaseapp.com',
    storageBucket: 'brain-boost-flashcard.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9N7QvihZ-mY-OGfzjkUcUQ5Y9keYCzEQ',
    appId: '1:912550072493:android:b4909bada926d864b4f624',
    messagingSenderId: '912550072493',
    projectId: 'brain-boost-flashcard',
    storageBucket: 'brain-boost-flashcard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYiwLXyD4Nx5gcntmCr-Z17k-5QRJ5zyg',
    appId: '1:912550072493:ios:bfdcf30e08b526f1b4f624',
    messagingSenderId: '912550072493',
    projectId: 'brain-boost-flashcard',
    storageBucket: 'brain-boost-flashcard.firebasestorage.app',
    iosBundleId: 'com.example.brainBoost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYiwLXyD4Nx5gcntmCr-Z17k-5QRJ5zyg',
    appId: '1:912550072493:ios:bfdcf30e08b526f1b4f624',
    messagingSenderId: '912550072493',
    projectId: 'brain-boost-flashcard',
    storageBucket: 'brain-boost-flashcard.firebasestorage.app',
    iosBundleId: 'com.example.brainBoost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcDDdNXYNd83QFnAWkIm65RRPpLqw6uCg',
    appId: '1:912550072493:web:9cd194f6289cd748b4f624',
    messagingSenderId: '912550072493',
    projectId: 'brain-boost-flashcard',
    authDomain: 'brain-boost-flashcard.firebaseapp.com',
    storageBucket: 'brain-boost-flashcard.firebasestorage.app',
  );
}
